In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

# Load some text data - from wikipedia, pages on people using pandas

In [80]:
people = pd.read_csv('people_wiki.csv')

In [81]:
# Data contains: link to wikipedia article, name of person, text of article.
people.head()

,URI,name,text
0,<http://dbpedia.org/resource/Digby_Morrell>,Digby Morrell,digby morrell born 10 october 1979 is a former...
1,<http://dbpedia.org/resource/Alfred_J._Lewy>,Alfred J. Lewy,alfred j lewy aka sandy lewy graduated from un...
2,<http://dbpedia.org/resource/Harpdog_Brown>,Harpdog Brown,harpdog brown is a singer and harmonica player...
3,<http://dbpedia.org/resource/Franz_Rottensteiner>,Franz Rottensteiner,franz rottensteiner born in waidmannsfeld lowe...
4,<http://dbpedia.org/resource/G-Enka>,G-Enka,henry krvits born 30 december 1974 in tallinn ...

In [82]:
#number of records in the dataset
len(people)

59071

# Explore the dataset and checkout the text it containsÂ¶
### Exploring the entry for president Obama

In [127]:
#people['name'].value_counts()
#people.name = people.name.str.replace(' *', '')
#people.sort_values('name')

In [128]:
obama = people[people['name']== 'Barack Obama']

In [129]:
obama

,URI,name,text
35817,<http://dbpedia.org/resource/Barack_Obama>,Barack Obama,barack hussein obama ii brk husen bm born augu...

In [130]:
obama['text'].values

array([ 'barack hussein obama ii brk husen bm born august 4 1961 is the 44th and current president of the united states and the first african american to hold the office born in honolulu hawaii obama is a graduate of columbia university and harvard law school where he served as president of the harvard law review he was a community organizer in chicago before earning his law degree he worked as a civil rights attorney and taught constitutional law at the university of chicago law school from 1992 to 2004 he served three terms representing the 13th district in the illinois senate from 1997 to 2004 running unsuccessfully for the united states house of representatives in 2000in 2004 obama received national attention during his campaign to represent illinois in the united states senate with his victory in the march democratic party primary his keynote address at the democratic national convention in july and his election to the senate in november he began his presidential campaign in 2007 and after a close primary campaign against hillary rodham clinton in 2008 he won sufficient delegates in the democratic party primaries to receive the presidential nomination he then defeated republican nominee john mccain in the general election and was inaugurated as president on january 20 2009 nine months after his election obama was named the 2009 nobel peace prize laureateduring his first two years in office obama signed into law economic stimulus legislation in response to the great recession in the form of the american recovery and reinvestment act of 2009 and the tax relief unemployment insurance reauthorization and job creation act of 2010 other major domestic initiatives in his first term included the patient protection and affordable care act often referred to as obamacare the doddfrank wall street reform and consumer protection act and the dont ask dont tell repeal act of 2010 in foreign policy obama ended us military involvement in the iraq war increased us troop levels in afghanistan signed the new start arms control treaty with russia ordered us military involvement in libya and ordered the military operation that resulted in the death of osama bin laden in january 2011 the republicans regained control of the house of representatives as the democratic party lost a total of 63 seats and after a lengthy debate over federal spending and whether or not to raise the nations debt limit obama signed the budget control act of 2011 and the american taxpayer relief act of 2012obama was reelected president in november 2012 defeating republican nominee mitt romney and was sworn in for a second term on january 20 2013 during his second term obama has promoted domestic policies related to gun control in response to the sandy hook elementary school shooting and has called for full equality for lgbt americans while his administration has filed briefs which urged the supreme court to strike down the defense of marriage act of 1996 and californias proposition 8 as unconstitutional in foreign policy obama ordered us military involvement in iraq in response to gains made by the islamic state in iraq after the 2011 withdrawal from iraq continued the process of ending us combat operations in afghanistan and has sought to normalize us relations with cuba'], dtype=object)

In [131]:
people.shape

(59071, 3)

In [132]:
#Get the word counts for Obama article
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
features = vectorizer.fit_transform(obama['text'])

In [133]:
features

<1x270 sparse matrix of type '<class 'numpy.int64'>'
	with 270 stored elements in Compressed Sparse Row format>

In [134]:
vocab = vectorizer.get_feature_names()

In [135]:
vocab

['13th',
 '1961',
 '1992',
 '1996',
 '1997',
 '20',
 '2000in',
 '2004',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2012obama',
 '2013',
 '44th',
 '63',
 'act',
 'address',
 'administration',
 'affordable',
 'afghanistan',
 'african',
 'after',
 'against',
 'american',
 'americans',
 'and',
 'arms',
 'as',
 'ask',
 'at',
 'attention',
 'attorney',
 'august',
 'barack',
 'before',
 'began',
 'bin',
 'bm',
 'born',
 'briefs',
 'brk',
 'budget',
 'by',
 'californias',
 'called',
 'campaign',
 'care',
 'chicago',
 'civil',
 'clinton',
 'close',
 'columbia',
 'combat',
 'community',
 'constitutional',
 'consumer',
 'continued',
 'control',
 'convention',
 'court',
 'creation',
 'cuba',
 'current',
 'death',
 'debate',
 'debt',
 'defeated',
 'defeating',
 'defense',
 'degree',
 'delegates',
 'democratic',
 'district',
 'doddfrank',
 'domestic',
 'dont',
 'down',
 'during',
 'earning',
 'economic',
 'election',
 'elementary',
 'ended',
 'ending',
 'equality',
 'federal',
 'filed',
 'first',
 'for',
 'foreign',
 'form',
 'from',
 'full',
 'gains',
 'general',
 'graduate',
 'great',
 'gun',
 'harvard',
 'has',
 'hawaii',
 'he',
 'hillary',
 'his',
 'hold',
 'honolulu',
 'hook',
 'house',
 'husen',
 'hussein',
 'ii',
 'illinois',
 'in',
 'inaugurated',
 'included',
 'increased',
 'initiatives',
 'insurance',
 'into',
 'involvement',
 'iraq',
 'is',
 'islamic',
 'january',
 'job',
 'john',
 'july',
 'keynote',
 'laden',
 'laureateduring',
 'law',
 'legislation',
 'lengthy',
 'levels',
 'lgbt',
 'libya',
 'limit',
 'lost',
 'made',
 'major',
 'march',
 'marriage',
 'mccain',
 'military',
 'mitt',
 'months',
 'named',
 'national',
 'nations',
 'new',
 'nine',
 'nobel',
 'nomination',
 'nominee',
 'normalize',
 'not',
 'november',
 'obama',
 'obamacare',
 'of',
 'office',
 'often',
 'on',
 'operation',
 'operations',
 'or',
 'ordered',
 'organizer',
 'osama',
 'other',
 'over',
 'party',
 'patient',
 'peace',
 'policies',
 'policy',
 'president',
 'presidential',
 'primaries',
 'primary',
 'prize',
 'process',
 'promoted',
 'proposition',
 'protection',
 'raise',
 'reauthorization',
 'receive',
 'received',
 'recession',
 'recovery',
 'reelected',
 'referred',
 'reform',
 'regained',
 'reinvestment',
 'related',
 'relations',
 'relief',
 'repeal',
 'represent',
 'representatives',
 'representing',
 'republican',
 'republicans',
 'response',
 'resulted',
 'review',
 'rights',
 'rodham',
 'romney',
 'running',
 'russia',
 'sandy',
 'school',
 'seats',
 'second',
 'senate',
 'served',
 'shooting',
 'signed',
 'sought',
 'spending',
 'start',
 'state',
 'states',
 'stimulus',
 'street',
 'strike',
 'sufficient',
 'supreme',
 'sworn',
 'taught',
 'tax',
 'taxpayer',
 'tell',
 'term',
 'terms',
 'that',
 'the',
 'then',
 'three',
 'to',
 'total',
 'treaty',
 'troop',
 'two',
 'unconstitutional',
 'unemployment',
 'united',
 'university',
 'unsuccessfully',
 'urged',
 'us',
 'victory',
 'wall',
 'war',
 'was',
 'where',
 'whether',
 'which',
 'while',
 'with',
 'withdrawal',
 'won',
 'worked',
 'years']

In [136]:
dist = np.sum(features.toarray(), axis=0)
dist

array([ 1,  1,  1,  1,  1,  2,  1,  3,  1,  1,  3,  2,  3,  1,  1,  1,  1,
        1,  8,  1,  1,  1,  2,  1,  4,  1,  3,  1, 21,  1,  6,  1,  2,  1,
        1,  1,  1,  1,  1,  1,  1,  2,  1,  1,  1,  1,  1,  1,  3,  1,  2,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  4,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  4,  1,  1,  2,  2,  1,  2,  1,  1,  3,  1,
        1,  1,  1,  1,  1,  3,  4,  2,  1,  3,  1,  1,  1,  1,  1,  1,  2,
        4,  1,  7,  1, 11,  1,  1,  1,  2,  1,  1,  1,  2, 30,  1,  1,  1,
        1,  1,  1,  3,  4,  2,  1,  3,  1,  1,  1,  1,  1,  1,  6,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  4,  1,  1,  1,  2,  1,  1,
        1,  1,  1,  2,  1,  1,  2,  9,  1, 18,  2,  1,  2,  1,  1,  1,  3,
        1,  1,  1,  1,  3,  1,  1,  1,  2,  4,  2,  1,  2,  1,  1,  1,  1,
        2,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  1,  1,
        2,  1,  2,  1,  3,  1,  1,  1,  1,  1,  1,  1,  1,  3,  1,  2,  3,
        2,  1,  3,  1,  1,  1,  1,  3,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  3,  1,  1, 40,  1,  1, 14,  1,  1,  1,  1,  1,  1,  3,  2,  1,
        1,  6,  1,  1,  1,  5,  1,  1,  1,  1,  3,  1,  1,  1,  1], dtype=int64)

In [137]:
#Sort the word counts for the Obama article
#Turning dictonary of word counts into a dataframe

obama_word_count_table = pd.DataFrame({'token':vocab, 'count':dist}).sort_values('count')

In [138]:
obama_word_count_table.sort_values('count', ascending=False).head(10)

     count  token
242     40    the
115     30     in
28      21    and
162     18     of
245     14     to
106     11    his
160      9  obama
18       8    act
104      7     he
133      6    law

# Compute TF-IDF for the corpus
### To give more weight to informative words, we weigh them by their TF-IDF scores.
### We'll vectorize the entire corpus and compute the TF-IDF in one step

In [139]:
from sklearn.feature_extraction.text import TfidfVectorizer
vect = TfidfVectorizer()

In [140]:
dtm = vect.fit_transform(people['text'])

In [141]:
dtm.shape

(59071, 548429)

In [142]:
features = vect.get_feature_names()

In [143]:
features

['00',
 '000',
 '0000',
 '00000',
 '00000van',
 '0001',
 '00014338',
 '0001sec',
 '0002',
 '00026',
 '0003',
 '0005',
 '000577',
 '0005sec',
 '0006',
 '0007',
 '0007105916',
 '0007200374',
 '0007207328',
 '0007213506',
 '000721426xhe',
 '0007a',
 '000he',
 '000in',
 '000m',
 '000seelenprojekt',
 '000tnmickushina',
 '001',
 '0017',
 '001cd',
 '001ehebbm',
 '002',
 '0020849605',
 '0024',
 '0026183900',
 '002864574x',
 '0028659287',
 '003',
 '0033',
 '0034',
 '0036',
 '004',
 '0043',
 '0046',
 '004erdemir',
 '005',
 '006',
 '0060222425',
 '0060628227',
 '0060628464',
 '0060669667',
 '006074393x',
 '0064',
 '0066',
 '007',
 '0070710481',
 '0071357440',
 '0071375627',
 '0072131772',
 '0072131896',
 '0072222611',
 '0072225351',
 '0072438886',
 '007all',
 '008',
 '0080',
 '0080357547',
 '008after',
 '009',
 '00906603',
 '0091',
 '0091857112',
 '0091900255she',
 '0099416689',
 '009at',
 '00a10',
 '00g',
 '00s',
 '00sex',
 '00sin',
 '01',
 '010',
 '0100',
 '01000400',
 '01011001',
 '01011001i',
 '0102',
 '0102928045since',
 '010397',
 '01041984',
 '010602he',
 '0108',
 '011',
 '0110',
 '01122005',
 '0113554',
 '011708',
 '012',
 '0123039606',
 '013',
 '013011510x',
 '0131232746',
 '0139738509',
 '014',
 '0140265708',
 '0140280553',
 '0143',
 '014a',
 '015',
 '0158',
 '016',
 '016a',
 '017',
 '017384251',
 '018',
 '0186',
 '0195104633dr',
 '0195140532winifred',
 '0198',
 '0198149417',
 '0198150784',
 '0198155409',
 '0198162073',
 '0198269862',
 '0198299966judaism',
 '01analyzing',
 '01consulting',
 '01he',
 '01jazz',
 '01kwh',
 '01net',
 '01oct1952',
 '01shave',
 '01st',
 '01w',
 '02',
 '020',
 '0200',
 '0201083191',
 '020114218x',
 '02011964',
 '020139829x',
 '0201498278he',
 '0201533774',
 '020158042x',
 '0201580438',
 '0201725932',
 '0202361373',
 '0203',
 '02032010',
 '0205',
 '0208',
 '021',
 '021050',
 '021206',
 '021207his',
 '02138',
 '02182748',
 '022',
 '022009',
 '02202020',
 '0225662434',
 '0225662434the',
 '0226727033',
 '022under',
 '023',
 '0231115113',
 '0233976817',
 '024',
 '0240804120winder',
 '0240814215',
 '024cd',
 '025',
 '0252009851we',
 '0252014278',
 '0252070003',
 '026',
 '0262195224',
 '0262521563',
 '0262524570',
 '027',
 '0273',
 '0273langton',
 '0275938514',
 '028',
 '0282',
 '029',
 '0295973390',
 '0295974982',
 '02au',
 '02he',
 '02the',
 '03',
 '030',
 '0300',
 '0300051115paul',
 '0304',
 '03072010',
 '03082008',
 '031',
 '0310227283',
 '0312022484',
 '0312038054',
 '0312151918',
 '0312199228',
 '0312360398',
 '0312913451',
 '0313313326professor',
 '031538736',
 '0316346624',
 '0316359564',
 '032',
 '0321186125an',
 '0321187911',
 '0321422775balancing',
 '0321461088cmmi',
 '033',
 '0330482688',
 '034',
 '034042320x',
 '0340428910',
 '0340500719',
 '0340524553',
 '0340551097',
 '0340565403',
 '0340579714',
 '0340579730',
 '0340628588',
 '0340832118',
 '0345373065waiting',
 '035',
 '036',
 '037',
 '0373892101',
 '0375411852joint',
 '03790',
 '038',
 '0380751089review',
 '038075343xreview',
 '0380755203as',
 '0380898527review',
 '03824',
 '038518011x',
 '0387',
 '0387942890',
 '0393039153',
 '0393058697',
 '039306073x',
 '0394537173the',
 '0394546032broadsides',
 '03945771243',
 '0395827442',
 '0395837030sue',
 '0395883245a',
 '0399513329',
 '039951810x',
 '03his',
 '04',
 '040',
 '0400',
 '04012015',
 '0403',
 '040407',
 '0405',
 '040612',
 '0407',
 '040he',
 '041',
 '04122006he',
 '0413776565bigsby',
 '0415049709',
 '042',
 '04242018',
 '04312417676',
 '0434',
 '04350925',
 '044',
 '0440223857netter',
 '0441',
 '0443073457',
 '0446329673',
 '0446696749',
 '045',
 '0450048047in',
 '04522599832',
 '046',
 '0465045677metzingers',
 '0465091148',
 '047',
 '0470179147',
 '0470540710moffitt',
 '0470834005',
 '0470838515',
 '0471250376',
 '0471417920',
 '0471489093',
 '0471597376in',
 '0471683345',
 '0471792519in',
 '0471833568',
 '0471971979',
 '0471971987',
 '0472114190shrinking',
 '048',
 '0485w',
 '0486',
 '049',
 '0499',
 '04journalist',
 '04nikon',
 '04s',
 '04th',
 '05',
 '050',
 '0500251126the',
 '0500274959',
 '0500506',
 '05012011',
 '050187',
 '0503',
 '0504',
 '05042008',
 '05042012',
 '0505',
 '0506',
 '050607',
 '051',
 '0512after',
 '0515',
 '05151992',
 '0517078074',
 '0517705427',
 '051989after',
 '052',
 '0520207343',
 '052020735',
 '0521207886matthew',
 '052124160x',
 '0521416957',
 '0521447828',
 '0521582741',
 '0521816262',
 '05222358230',
 '052284085x',
 '052340347x',
 '0529',
 '053shis',
 '055',
 '0555',
 '05564',
 '0557049148',
 '0559',
 '056',
 '057',
 '0571147763',
 '0578054043',
 '0586069984',
 '059',
 '0595089003',
 '059534819x',
 '0595351689',
 '0595376053',
 '0595760260',
 '0595760260my',
 '05b',
 '05bn',
 '05festival',
 '05following',
 '05he',
 '05kean',
 '05m',
 '05maio',
 '05the',
 '06',
 '060',
 '0600545',
 '060218',
 '06021960',
 '06021999',
 '060508',
 '06052008',
 '06052011',
 '0606jason',
 '0607',
 '061',
 '0611',
 '0613',
 '06140',
 '0615202136',
 '0618378294',
 '0618391118',
 '0618446621',
 '0618453695',
 '0618717609',
 '062',
 '063',
 '06301000',
 '0632037571',
 '0637',
 '064',
 '0643704',
 '0646043099',
 '0646157116',
 '0646190296',
 '0646352601',
 '0646464817guy',
 '065',
 '066',
 '0667',
 '067',
 '0670043281',
 '0676975216',
 '0679400036',
 '0679400621farflung',
 '0679424652',
 '067942833xfrom',
 '068',
 '0683',
 '0689106165in',
 '069',
 '0691070075',
 '0691091293',
 '0692337008',
 '06he',
 '06in',
 '06m',
 '07',
 '070',
 '0700',
 '0705',
 '07051978',
 '07072014',
 '0708',
 '071',
 '0710',
 '0711',
 '0714542954',
 '0714masella',
 '0715631330',
 '071670076xdudley',
 '0727907867his',
 '07292011',
 '073',
 '0738210447',
 '074',
 '0743246950',
 '0743260481',
 '0743271165',
 '0743287150',
 '0743290429',
 '0743466330',
 '0743470591',
 '074756695x',
 '0748663215',
 '075',
 '0750310219',
 '0750944064',
 '0750946741',
 '0750947497',
 '0752450077',
 '0752457403',
 '0752463527',
 '0754',
 '0754631222',
 '0758202709',
 '0758216599',
 '076',
 '0761839674',
 '0762',
 '076241541x',
 '0765311704stemple',
 '077',
 '0771016573',
 '0771065094in',
 '0773478396prior',
 '0773507450bakan',
 '0773522522',
 '0773731911',
 '0773gtafter',
 '078',
 '0786607335',
 '0793',
 '079second',
 '07ghost',
 '07in',
 '07s',
 '08',
 '080',
 '0801057647jesus',
 '0801495427',
 '0801862701',
 '0802075959',
 '0802111068',
 '0802807356mark',
 '080283549xisbn',
 '0802836984first',
 '0802849806the',
 '0803747527',
 '0803938845',
 '0803972059',
 '0804115559',
 '0805791086',
 '0806901551',
 '0806903449',
 '0806904127',
 '080690724x',
 '0806913045',
 '080691811x',
 '080692893x',
 '0806964979',
 '0806969830',
 '0806984686',
 '0806985429',
 '0806987529',
 '0806989491',
 '0806997117',
 '0807',
 '0807031119her',
 '08072013',
 '0808',
 '0809',
 '080972',
 '080m',
 '081',
 '0810867214',
 '0811213420the',
 '0811364',
 '0811814157',
 '0811848752',
 '0812235304',
 '0812908910',
 '0812991583',
 '0813333024roman',
 '08142013',
 '0815603878rudolf',
 '0815focus',
 '0816030936',
 '0816038465',
 '0819184454',
 '081988',
 '082',
 '082011',
 '082012',
 '0820449148',
 '0821258303',
 '0822317206',
 '0825611547',
 '0826464637',
 '0826470459',
 '0827244940',
 '083',
 '08337029',
 '0838905900',
 '084',
 '0841218366streitwieser',
 '0842517901',
 '0843909196deadpan',
 '084390948xstopgap',
 '0843909722as',
 '0847819876',
 '0849333261',
 '085',
 '0851989136',
 '0852346492',
 '0853033803',
 '0853459215',
 '0855',
 '085he',
 '086',
 '0862434955',
 '0867',
 '0868409707',
 '087',
 '0877226504global',
 '0877227756communities',
 '0877229457',
 '0877736103the',
 '0877736707harmonic',
 '0878332642',
 '0878332928',
 '0879101733',
 '0879759712',
 '088',
 '0881507032fine',
 '0881507423',
 '0883441888',
 '0883441888prof',
 '0883850877',
 '0883852020',
 '0883855070',
 '0883855143',
 '0883855240',
 '08891027912',
 '0889202206',
 '0889820228',
 '0889991499',
 '0889994536',
 '0889995737',
 '089',
 '0892561661horchow',
 '0892815604bridge',
 '0894',
 '0897501446',
 '0898230497',
 '0898655641',
 '08bn06bn',
 '08chris',
 '08in',
 '08ppgjurevicus',
 '08though',
 '09',
 '090',
 '0900',
 '09008050',
 '090182514x',
 '0902',
 '0906456002',
 '0906other',
 '09081968',
 '0908630360',
 '091',
 '0910',
 '0911',
 '09112014',
 '091160136',
 '091299',
 '091364',
 '0915368552',
 '0916217361as',
 '0918432871',
 '0920',
 '092064art',
 '0922',
 '09223',
 '0929712242he',
 '093',
 '09301230',
 '0930407571',
 '0931425379taub',
 '0935067140',
 '09366',
 '0938768336',
 '094',
 '0944803733ted',
 '095',
 '0952122642',
 '0953695158the',
 '0953743829',
 '0953979806',
 '0954407555',
 '0955048206',
 '096',
 '0961862203kathy',
 '0964793059',
 '096479308',
 '0967202957',
 '096720299x',
 '0968337309',
 '0968568904',
 '097',
 '0970276834',
 '0971509328',
 '0972140204',
 '0972178902',
 '0972669345',
 '097268221x',
 '0974670103',
 '0975578405',
 '097746170x',
 '0978240519289',
 '098',
 '099',
 '0998',
 '0999',
 '09areas',
 '09both',
 '09m',
 '09szhkb',
 '09the',
 '0b',
 '0chandigarh',
 '0dimensional',
 '0draws',
 '0f',
 '0fer',
 '0for1',
 '0for13',
 '0for1he',
 '0for2',
 '0for20',
 '0for3',
 '0for4',
 '0for5',
 '0for7',
 '0for8',
 '0g',
 '0mahaffey',
 '0n',
 '0one',
 '0rphandrift',
 '0rphandrifts',
 '0sle',
 '0wner',
 '0x10c',
 '10',
 '100',
 '1000',
 '10000',
 '100000',
 '1000000',
 '10000000',
 '100000000',
 '1000000000',
 '10000000000',
 '10000000prior',
 '1000000he',
 '1000000in',
 '1000000jeff',
 '1000000mckeever',
 '100000and',
 '100000at',
 '100000best',
 '100000garners',
 '100000harrington',
 '100000in',
 '100000mile',
 '100000papathanassiou',
 '100000pappas',
 '100000resident',
 '100000the',
 '100000verse',
 '100000vote',
 '100001996',
 '1000020000',
 '10000ayear',
 '10000he',
 '10000in',
 '10000jata',
 '10000km',
 '10000m',
 '10000m10000',
 '10000meter',
 '10000metre',
 '10000mgrage',
 '10000seat',
 '10000th',
 '10000tommy',
 '10000word',
 '10000year',
 '10001100pm',
 '10001300',
 '10001400',
 '10001500',
 '10001536',
 '10002500',
 '100050',
 '10006',
 '10007',
 '1000900',
 '1000acre',
 '1000am1230pm',
 '1000andrew',
 '1000bed',
 '1000cc',
 '1000ellsworth',
 '1000eventi',
 '1000holmsen',
 '1000hp',
 '1000in',
 '1000km',
 '1000le',
 '1000m',
 '1000meter',
 '1000metre',
 '1000mw',
 '1000noon',
 '1000oaksbarrelcom',
 '1000page',
 '1000plus',
 '1000pm',
 '1000point',
 '1000pointrebound',
 '1000prosecutors',
 '1000reggie',
 '1000run',
 '1000s',
 '1000squarefoot',
 '1000th',
 '1000the',
 '1000ukt',
 '1000win',
 '1000yard',
 '1000year',
 '1001',
 '100100',
 '100106',
 '100109the',
 '100112',
 '10011he',
 '1001500m',
 '100165',
 '10017',
 '1001the',
 '1002',
 '10020',
 '100200',
 '100200and',
 '10022012',
 '10023',
 '10024',
 '100250',
 '10028',
 '1003',
 '100300',
 '10030they',
 '10038',
 '1004',
 '10043',
 '10044',
 '100464',
 '1004he',
 '1004w',
 '1005',
 '10054',
 '10057',
 '1005fm',
 '1006',
 '10061',
 '100626',
 '10064',
 '10066',
 '1007',
 '10071012',
 '100724',
 '1007633mose',
 '10077',
 '1008',
 '10081',
 '10083',
 '1008robert',
 '1009',
 '10090',
 '10093',
 '10099',
 '100a',
 '100acre',
 '100after',
 '100although',
 '100at',
 '100b',
 '100bed',
 '100cc',
 '100clue',
 '100cyrus',
 '100day',
 '100dbs',
 '100defever',
 '100design',
 '100digit',
 '100e',
 '100following',
 '100foot',
 '100game',
 '100garland',
 '100girls',
 '100he',
 '100hour',
 '100in',
 '100inch',
 '100issue',
 '100k',
 '100kenny',
 '100kg',
 '100kilometre',
 '100km',
 '100largest',
 '100lbs',
 '100lingmerth',
 '100lovato',
 '100m',
 '100mbits',
 '100megawatt',
 '100meter',
 '100metre',
 '100mev',
 '100mgilbert',
 '100mhz',
 '100mile',
 '100miler',
 '100million',
 '100ml',
 '100mlater',
 '100mon',
 '100mph',
 '100mshe',
 '100odd',
 '100p196869',
 '100page',
 '100pages',
 '100percent',
 '100person',
 '100piece',
 '100pm',
 '100point',
 '100ragnarsdottir',
 '100rbi',
 '100reception',
 '100s',
 '100seat',
 '100she',
 '100story',
 '100strong',
 '100t',
 '100th',
 '100thaning',
 '100thanniversary',
 '100the',
 '100thyear',
 '100to1',
 '100to70isora',
 '100varbles',
 '100voice',
 '100watt',
 '100whfs',
 '100while',
 '100williams',
 '100williamss',
 '100winner',
 '100word',
 '100y',
 '100yard',
 '100yd',
 '100year',
 '100yearold',
 '101',
 '1010',
 '10100',
 '101000',
 '101000kilometre',
 '101002job1813',
 '10101',
 '101010',
 '1010200311012004',
 '10102014',
 '10106',
 '10107',
 '10108',
 '1010committee',
 '1010s',
 '1011',
 '1011000',
 '101106',
 '10111',
 '101111eci12171',
 '101111jiec12196',
 '101117',
 '10114',
 '10115',
 '10116',
 '1011886',
 '10119',
 '101194',
 '101198101798cadrez',
 '1011994',
 '1011th',
 '1012',
 '10120',
 '10121',
 '1012181927',
 '10124at',
 '10125he',
 '10126',
 '1013',
 '10131',
 '1013249perrys',
 '101328',
 '10134',
 '10135',
 '10136',
 '10137',
 '101385',
 '1014',
 '10140',
 '1014000',
 '10141',
 '10145',
 '10147',
 '10148',
 '1015',
 '10150',
 '10153',
 '1015310163',
 '10156',
 '10156on',
 '10157',
 '1016',
 '10160',
 '101688',
 '1017',
 '10177',
 ...]

In [144]:
#Examine the TF-IDF for the Obama article
#Remember that the Obama article is at index 35817
obama

,URI,name,text
35817,<http://dbpedia.org/resource/Barack_Obama>,Barack Obama,barack hussein obama ii brk husen bm born augu...

In [145]:
#So we'll examine the document term matrix at index 35817 and pull out the TF-IDF by each word.
#First we'll make a dictionary
word_scores = {}
for word in vocab:
    word_scores[word] = dtm[35817, features.index(word)]

In [146]:
obama_word_scores = pd.DataFrame(list(word_scores.items()),
                      columns=['word', 'tfidf'])

In [148]:
obama_word_scores.sort_values('tfidf', ascending=False).head(10)

        word     tfidf
140    obama  0.365018
156      the  0.279323
157      act  0.249089
209       in  0.209673
76      iraq  0.151809
82       and  0.146739
216      law  0.144687
34   control  0.131857
67        of  0.126205
184       us  0.122834

In [149]:
vect = TfidfVectorizer(stop_words = 'english')
dtm = vect.fit_transform(people['text'])
features = vect.get_feature_names()

In [150]:
dtm.shape

(59071, 548115)

In [151]:
word_scores = {}
for word in vocab:
    if word in features: # vocab contains stop words that are no longer in our dtm
        word_scores[word] = dtm[35817, features.index(word)]

In [152]:
obama_word_scores = pd.DataFrame(list(word_scores.items()),
                      columns=['word', 'tfidf'])

In [153]:
obama_word_scores.sort_values('tfidf', ascending=False).head(10)

            word     tfidf
119        obama  0.413495
134          act  0.282170
61          iraq  0.171970
181          law  0.163903
113      control  0.149369
196      ordered  0.138633
217     military  0.135368
30    democratic  0.129792
66      response  0.124821
31   involvement  0.124821

# Manually compute similarity and distances between a few people
### Let's manually compare the similarity and distances between the articles for a few famous people.

In [154]:
#Is Obama closer to Clinton than to Beckham?
#Note that we're computing the cosine similarity (which ranges from 0 to 1, where 1 is most similar) not the cosine distance which we can use as well.
#cosine_distance = (1-cosine_similarity)
#We should find that the article about president Obama is closer to the one about former president Clinton than that of footballer David Beckham.


from sklearn.metrics.pairwise import cosine_similarity
clinton = people[people['name'] == 'Bill Clinton']
clooney = people[people['name'] == 'George Clooney']

In [155]:
cosine_similarity(dtm[obama.index], dtm[clinton.index])

array([[ 0.18896718]])

In [156]:
cosine_similarity(dtm[obama.index], dtm[clooney.index])

array([[ 0.0376872]])

In [157]:
#cosine distance
from sklearn.metrics.pairwise import pairwise_distances
pairwise_distances(dtm[obama.index], dtm[clinton.index], metric='cosine')

array([[ 0.81103282]])

In [158]:
pairwise_distances(dtm[obama.index], dtm[clooney.index], metric='cosine')

array([[ 0.9623128]])

In [159]:
#Build a nearest neighbor model for document retrievalÂ¶
dtm.shape

(59071, 548115)

In [160]:
from sklearn.neighbors import NearestNeighbors
neighbors = NearestNeighbors(n_neighbors=10)

In [161]:
neighbors.fit(dtm)

NearestNeighbors(algorithm='auto', leaf_size=30, metric='minkowski',
         metric_params=None, n_jobs=1, n_neighbors=10, p=2, radius=1.0)

In [162]:
#Who is closest to Obama?
distances, indices = neighbors.kneighbors(dtm[obama.index], return_distance=True)

In [163]:
distances

array([[ 0.        ,  1.16514466,  1.2073695 ,  1.21963978,  1.22250901,
         1.23617841,  1.24305659,  1.24466747,  1.24829554,  1.25160692]])

In [164]:
indices

array([[35817, 24478, 38376, 57108, 38714, 46140, 18827, 44681,  6796,
         2412]])

In [167]:
closest_people = zip(people.iloc[indices[0]]['name'], distances[0])

In [168]:
print(list(closest_people))

[('Barack Obama', 0.0), ('Joe Biden', 1.16514466168904), ('Samantha Power', 1.2073694972352877), ('Hillary Rodham Clinton', 1.2196397836767039), ('Eric Stern (politician)', 1.2225090075525111), ('Robert Gibbs', 1.2361784064861678), ('Henry Waxman', 1.2430565883007181), ('Jesse Lee (politician)', 1.244667471314294), ('Eric Holder', 1.248295535663575), ('Joe the Plumber', 1.2516069176926294)]